name: Terraform Deployment

on:
  pull_request:
    branches:
      - main  # Change this to your default branch if different
  push:
    branches:
      - main  # Change this to your default branch if different
permissions:
  id-token: write

jobs:
  terraform-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.8.4  # Consistent Terraform version

      - name: List Terraform Directory
        run: ls -al terraform  # Debug step

      - name: Terraform Format Check
        run: terraform fmt -check
        working-directory: terraform

  terraform-plan:
    runs-on: ubuntu-latest
    needs: terraform-check  # Ensure this job runs after the check
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.8.4  # Use consistent version

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::767397941516:role/GithubActionsRole  # Update with your role ARN
          aws-region: eu-west-3  # Change this to your desired AWS region

      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: terraform

  terraform-apply:
    runs-on: ubuntu-latest
    needs: terraform-plan
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.8.4  # Use consistent version

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::767397941516:role/GithubActionsRole  # Update with your role ARN
          aws-region: eu-west-3  # Change this to your desired AWS region

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        working-directory: terraform
        env:
          TF_VAR_example: ${{ secrets.EXAMPLE_SECRET }}
